### ISSUE TITLE
Provide override to change list separator 

### ISSUE THREAD

**Issue by mtnrbq** [demystifyfp/FsConfig#1]
### Description
I have legacy apps using  ';' as a list separator

### Expected behavior

Ideally, I'd like to be able to specify a list separator, e.g. in a similar way to how the environment variable name separator is specified:

    [<Convention("FSTWEET", Separator="-",ListSeparator=";")>]

### Actual behavior
Current implementation only supports ',' as list separator

### Known workarounds
No known workaround

I'm happy to submit a PR for the change if you believe it is worthwhile

**Comment by demystifyfp** [comment]
Hi @mtnrbq,
Sorry for the delayed response. I was on a short vacation.
It makes sense and I am looking forward to merging your PR.

One suggestion, instead of having the `ListSeparator` attribute at the record level, can we have it on the field level like the [CustomName attribute](https://github.com/demystifyfp/FsConfig/blob/0.0.4/src/FsConfig/Config.fs#L18) and use it like [this](https://github.com/demystifyfp/FsConfig/blob/0.0.4/src/FsConfig/Config.fs#L193-L201)?

**Comment by demystifyfp** [comment]
Once again thanks @mtnrbq for the PR. The updated version has been pushed to NuGet and It will be available shortly.
