### ISSUE TITLE
Docs link is broken

### ISSUE THREAD

**Issue by jkone27** [demystifyfp/FsConfig#31]
https://www.demystifyfp.com/FsConfig/ --> 404

**Comment by queil** [comment]
@tamizhvendan I have no access to GitHub Pages setup and [this workflow](https://github.com/demystifyfp/FsConfig/actions/runs/5302894559) seems to have run automatically wiping out the docs. Is there anything you can do?

**Comment by queil** [comment]
I can see that the docs are available at https://www.demystifyfp.com/FsConfig/content/index.html rather than root

**Comment by tamizhvendan** [comment]
@queil It looks like it has been broken for a long time. 

The static site is set for the `docs` folder, and it is pointing to `https://www.demystifyfp.com/FsConfig.` Since the generated `index.html` is available inside the `content` folder, we need to use the additional path to render it. We should be good if we can change the auto-generation logic to generate the files inside the `docs` folder!

**Comment by queil** [comment]
Fixed by https://github.com/demystifyfp/FsConfig/commit/b1fbcfab8f27e0c13e5038a2bbd38b3911f8441a

@jkone27
